### ISSUE TITLE
coding issues

### ISSUE THREAD

**Issue by puppala-koushik** [AlexzanderFlores/Worn-Off-Keys-Discord-Js#4]
my bot is not working properly as i did what you said

**Comment by elli0t43** [comment]
> my bot is not working properly as i did what you said

same happend with me...i don't get any welcome message shown

**Comment by Greazi-Dev** [comment]
oke so guys make a repository on your github and shar it here than I will take a look

**Comment by ROLIKDC** [comment]
Guys, please, go to developer portal at https://discord.com/developers , select your app, then go "BOT" page, and set "SERVER MEMBERS INTENT" - ON, and "PRESENCE INTENT" - ON

**Comment by ROLIKDC** [comment]
Close issue

**Comment by ROLIKDC** [comment]
It's not coding problems

**Comment by Galaxy-Coding** [comment]
@koushikpuppala5 @elli0t43 show us your source code please

**Comment by ROLIKDC** [comment]
Ok, im Leave this issue. Sorry, but all cant read like 2 years old, i deleted message with fix.

**Comment by MysticIsSus** [comment]
Hello everyone, ever since Alex made this video, Discord has made it so that INTENTS must be used when using the 'guildMemberAdd' events and so on, make sure to enable the intents on the developers page.
